In [1]:
import scipy.io
import pandas as pd
import numpy as np

In [2]:
import scipy.io
labels_mat = scipy.io.loadmat('imagelabels.mat')
splits_mat = scipy.io.loadmat('setid.mat')

In [3]:
label_indices = np.squeeze(labels_mat['labels'])
train_indices = np.squeeze(splits_mat['trnid'])
valid_indices = np.squeeze(splits_mat['valid'])
test_indices = np.squeeze(splits_mat['tstid'])
print(label_indices.shape)

(8189,)


In [4]:
print(label_indices.size == train_indices.size + valid_indices.size + test_indices.size)

True


In [5]:
for key, value in splits_mat.items():
    print(value)

b'MATLAB 5.0 MAT-file, Platform: GLNX86, Created on: Thu Feb 19 17:38:58 2009'
1.0
[]
[[6765 6755 6768 ... 8026 8036 8041]]
[[6773 6767 6739 ... 8028 8008 8030]]
[[6734 6735 6737 ... 8044 8045 8047]]


In [6]:
len(train_indices)
train_indices

array([6765, 6755, 6768, ..., 8026, 8036, 8041], dtype=uint16)

In [7]:
label_indices_df = pd.DataFrame({'image':np.arange(1, len(label_indices)+1), 'label':label_indices})
label_indices_df

image  label
0         1     77
1         2     77
2         3     77
3         4     77
4         5     77
...     ...    ...
8184   8185     62
8185   8186     62
8186   8187     62
8187   8188     62
8188   8189     62

[8189 rows x 2 columns]

In [8]:
train_indices_df = pd.DataFrame({'train':train_indices})
valid_indices_df = pd.DataFrame({'valid':valid_indices})
test_indices_df = pd.DataFrame({'test':test_indices})
display(train_indices_df)
len(train_indices)

train
0      6765
1      6755
2      6768
3      6736
4      6744
...     ...
1015   8004
1016   8013
1017   8026
1018   8036
1019   8041

[1020 rows x 1 columns]

1020

In [9]:
indices_df = label_indices_df.copy()
indices_df['train'] = label_indices_df['image'].isin(train_indices_df['train']).astype(int)
indices_df[indices_df['train']==1]

image  label  train
27       28     77      1
35       36     77      1
78       79     77      1
115     116     77      1
117     118     77      1
...     ...    ...    ...
8164   8165     62      1
8165   8166     62      1
8166   8167     62      1
8174   8175     62      1
8176   8177     62      1

[1020 rows x 3 columns]

In [10]:
print(sum(indices_df['train']))
display(indices_df)

1020


image  label  train
0         1     77      0
1         2     77      0
2         3     77      0
3         4     77      0
4         5     77      0
...     ...    ...    ...
8184   8185     62      0
8185   8186     62      0
8186   8187     62      0
8187   8188     62      0
8188   8189     62      0

[8189 rows x 3 columns]

In [11]:
indices_df['valid'] = indices_df['image'].isin(valid_indices_df['valid']).astype(int)
indices_df['test'] = indices_df['image'].isin(test_indices_df['test']).astype(int)

In [12]:
display(indices_df)

image  label  train  valid  test
0         1     77      0      0     1
1         2     77      0      0     1
2         3     77      0      0     1
3         4     77      0      0     1
4         5     77      0      0     1
...     ...    ...    ...    ...   ...
8184   8185     62      0      1     0
8185   8186     62      0      0     1
8186   8187     62      0      1     0
8187   8188     62      0      0     1
8188   8189     62      0      0     1

[8189 rows x 5 columns]

In [13]:
# checking that train, valid, test columns and their source arrays have the same number of values
print(len(train_indices) == sum(indices_df['train']))
print(len(valid_indices) == sum(indices_df['valid']))
print(len(test_indices) == sum(indices_df['test']))

True
True
True


In [14]:
# checking for mutual exclusivity between image splits (each image is either train, valid, or test data)
print(indices_df['train'] + indices_df['valid'] + indices_df['test'])
print(min(indices_df['train'] + indices_df['valid'] + indices_df['test']))
print(max(indices_df['train'] + indices_df['valid'] + indices_df['test']))

0       1
1       1
2       1
3       1
4       1
       ..
8184    1
8185    1
8186    1
8187    1
8188    1
Length: 8189, dtype: int32
1
1


In [15]:
print(len(train_indices))
print(len(valid_indices))
print(len(test_indices))

1020
1020
6149


In [20]:
# Building training, validation, and testing filename lists:
train_files = [f'image_{x:05d}.jpg' for x in train_indices]
valid_files = [f'image_{x:05d}.jpg' for x in train_indices]
test_files = [f'image_{x:05d}.jpg' for x in train_indices]
print(train_files[0:9])

['image_06765.jpg', 'image_06755.jpg', 'image_06768.jpg', 'image_06736.jpg', 'image_06744.jpg', 'image_06766.jpg', 'image_06771.jpg', 'image_06750.jpg', 'image_06741.jpg']
